language: android

jdk:
- oraclejdk8

android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28
  licenses:
  - ".+"

script:
- "./gradlew assembleDebug"

notifications:
  email: false

sudo: required

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$ANDROID_HOME"

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"